### ISSUE TITLE
پیشنهادات برای ریپو 

### ISSUE THREAD

**Issue by Mohammadgeek** [Mohammadgeek/cli_cheatsheet#1]
سلام به نظرتون چه کارهای برای بهتر شدن ریپو میشه کرد؟!

**Comment by MobinaJafarian** [comment]
سلام 
میشه دستورات بیشتری مثل Permissions و Network و ... اضافه بشه.
و یه پیشنهاد دیگه که می تونه جذاب باشه دستورات OS های مختلف و **تفاوت** بینشون.

**Comment by Mohammadgeek** [comment]
> سلام میشه دستورات بیشتری مثل Permissions و Network و ... اضافه بشه. و یه پیشنهاد دیگه که می تونه جذاب باشه دستورات OS های مختلف و **تفاوت** بینشون.

کامندهای شبکه اطلاع دارم ولی اون Permissions دقیقا نمیدونم چیه منظورتونه ؟

**Comment by MobinaJafarian** [comment]
پرمیشن های فایل و فولدر ها چندتا مثال : 
R – Read.
W – Write.
C – Change (write)
F – Full control.

**Comment by Mohammadgeek** [comment]
> پرمیشن های فایل و فولدر ها چندتا مثال : R – Read. W – Write. C – Change (write) F – Full control.

بله متوجه شدم ! اگه وقت دارید ممنون میشم اضافه کنید من دستورات شبکه حتما اضافه میکنم :)
